Runs OK Redirects to static page > mvn tomcat7:deploy to create WAR and run in tomcat > 7 NB Will not run in tomcat 7. Cause: tomcat7 does not support the servlet version. See https://stackoverflow.com/questions/67026939/spring-tomcat-nosuchmethoderror-setcontentlengthlong